before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goamd64:
      - v1
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Revision={{ .ShortCommit }}
      - -X github.com/prometheus/common/version.Branch={{ .Branch }}
      - -X github.com/prometheus/common/version.BuildUser={{ .Env.USER }}
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}
gomod:
  proxy: true
dockers:
  - image_templates:
      - halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/halkyon/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/halkyon/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
    goos: linux
    goarch: arm
    goarm: 6
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v6
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/halkyon/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/halkyon/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/halkyon/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/halkyon/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: halkyon/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
      - halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
      - halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: halkyon/{{ .ProjectName }}:latest
    image_templates:
      - halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
      - halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
      - halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/halkyon/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: checksums_sha256.txt
  algorithm: sha256
source:
  enabled: true
sboms:
  - artifacts: archive
  - id: source
    artifacts: source
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: checksum
    output: true
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign"
      - "${artifact}"
    artifacts: images
    output: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
