name: analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 11 * * 2'
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.0.2
      - uses: github/codeql-action/init@b398f525a5587552e573b247ac661067fafa920b # v2.1.22
      - uses: github/codeql-action/autobuild@b398f525a5587552e573b247ac661067fafa920b # v2.1.22
      - uses: github/codeql-action/analyze@b398f525a5587552e573b247ac661067fafa920b # v2.1.22
