name: analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 11 * * 2'
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: github/codeql-action/init@b398f525a5587552e573b247ac661067fafa920b # v2.1.21
      - uses: github/codeql-action/autobuild@b398f525a5587552e573b247ac661067fafa920b # v2.1.21
      - uses: github/codeql-action/analyze@b398f525a5587552e573b247ac661067fafa920b # v2.1.21
