name: analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 11 * * 2'
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: github/codeql-action/init@0c670bbf0414f39666df6ce8e718ec5662c21e03 # v2.1.16
      - uses: github/codeql-action/autobuild@0c670bbf0414f39666df6ce8e718ec5662c21e03 # v2.1.16
      - uses: github/codeql-action/analyze@0c670bbf0414f39666df6ce8e718ec5662c21e03 # v2.1.16
