name: analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 11 * * 2'
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: github/codeql-action/init@75b4f1c4669133dc294b06c2794e969efa2e5316 # v2.1.10
      - uses: github/codeql-action/autobuild@75b4f1c4669133dc294b06c2794e969efa2e5316 # v2.1.10
      - uses: github/codeql-action/analyze@75b4f1c4669133dc294b06c2794e969efa2e5316 # v2.1.10
