name: analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 11 * * 2'
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: github/codeql-action/init@cc7986c02bac29104a72998e67239bb5ee2ee110 # v2.1.22
      - uses: github/codeql-action/autobuild@cc7986c02bac29104a72998e67239bb5ee2ee110 # v2.1.22
      - uses: github/codeql-action/analyze@cc7986c02bac29104a72998e67239bb5ee2ee110 # v2.1.22
