name: analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 11 * * 2'
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.1
      - uses: github/codeql-action/init@1ed1437484560351c5be56cf73a48a279d116b78 # v2.1.8
      - uses: github/codeql-action/autobuild@1ed1437484560351c5be56cf73a48a279d116b78 # v2.1.8
      - uses: github/codeql-action/analyze@1ed1437484560351c5be56cf73a48a279d116b78 # v2.1.8
