name: analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 11 * * 2'
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: github/codeql-action/init@c7f292ea4f542c473194b33813ccd4c207a6c725 # v2.1.18
      - uses: github/codeql-action/autobuild@c7f292ea4f542c473194b33813ccd4c207a6c725 # v2.1.18
      - uses: github/codeql-action/analyze@c7f292ea4f542c473194b33813ccd4c207a6c725 # v2.1.18
