name: analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 11 * * 2'
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: github/codeql-action/init@6a38b7d4a1af70deb1b561eb77db2b5e5a6a1e69 # v2.1.22
      - uses: github/codeql-action/autobuild@6a38b7d4a1af70deb1b561eb77db2b5e5a6a1e69 # v2.1.22
      - uses: github/codeql-action/analyze@6a38b7d4a1af70deb1b561eb77db2b5e5a6a1e69 # v2.1.22
