name: analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 11 * * 2'
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: github/codeql-action/init@41a4ada31ba866a7f1196b9602703a89edd69e22 # v2.1.12
      - uses: github/codeql-action/autobuild@41a4ada31ba866a7f1196b9602703a89edd69e22 # v2.1.12
      - uses: github/codeql-action/analyze@41a4ada31ba866a7f1196b9602703a89edd69e22 # v2.1.12
